/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author tomor
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Opcion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TComidas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        desayuno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        almuerzo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cena = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        añadirAlimentos1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tusActividades = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ejercicios = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        actividades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pasos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        resumen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        registrarActividades = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tusActividades1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pasos1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        actividades1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        ejercicios1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        resumen1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(243, 156, 18));

        Titulo.setBackground(new java.awt.Color(255, 153, 0));
        Titulo.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 60)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText(" FRC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 700, 50));

        Opcion.setBackground(new java.awt.Color(255, 153, 0));
        Opcion.setPreferredSize(new java.awt.Dimension(51, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Opciones.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout OpcionLayout = new javax.swing.GroupLayout(Opcion);
        Opcion.setLayout(OpcionLayout);
        OpcionLayout.setHorizontalGroup(
            OpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OpcionLayout.setVerticalGroup(
            OpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TComidas.setBackground(new java.awt.Color(133, 193, 233));
        TComidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("   Tus comidas");

        javax.swing.GroupLayout TComidasLayout = new javax.swing.GroupLayout(TComidas);
        TComidas.setLayout(TComidasLayout);
        TComidasLayout.setHorizontalGroup(
            TComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TComidasLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );
        TComidasLayout.setVerticalGroup(
            TComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TComidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(TComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 730, 50));

        desayuno.setBackground(new java.awt.Color(255, 255, 255));
        desayuno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("   Desayunos");

        javax.swing.GroupLayout desayunoLayout = new javax.swing.GroupLayout(desayuno);
        desayuno.setLayout(desayunoLayout);
        desayunoLayout.setHorizontalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desayunoLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 380, Short.MAX_VALUE))
        );
        desayunoLayout.setVerticalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(desayuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 730, 50));

        almuerzo.setBackground(new java.awt.Color(255, 255, 255));
        almuerzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("   Almuerzo");

        javax.swing.GroupLayout almuerzoLayout = new javax.swing.GroupLayout(almuerzo);
        almuerzo.setLayout(almuerzoLayout);
        almuerzoLayout.setHorizontalGroup(
            almuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almuerzoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        almuerzoLayout.setVerticalGroup(
            almuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, almuerzoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(almuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 730, 50));

        cena.setBackground(new java.awt.Color(255, 255, 255));
        cena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("   Cena");

        javax.swing.GroupLayout cenaLayout = new javax.swing.GroupLayout(cena);
        cena.setLayout(cenaLayout);
        cenaLayout.setHorizontalGroup(
            cenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenaLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        cenaLayout.setVerticalGroup(
            cenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cenaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(cena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 730, 50));

        añadirAlimentos1.setBackground(new java.awt.Color(255, 255, 255));
        añadirAlimentos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("                 Cambiar/Añadir alimetos");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout añadirAlimentos1Layout = new javax.swing.GroupLayout(añadirAlimentos1);
        añadirAlimentos1.setLayout(añadirAlimentos1Layout);
        añadirAlimentos1Layout.setHorizontalGroup(
            añadirAlimentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirAlimentos1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        añadirAlimentos1Layout.setVerticalGroup(
            añadirAlimentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, añadirAlimentos1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(añadirAlimentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 330, 40));

        tusActividades.setBackground(new java.awt.Color(133, 193, 233));
        tusActividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("   Tus actividades");

        javax.swing.GroupLayout tusActividadesLayout = new javax.swing.GroupLayout(tusActividades);
        tusActividades.setLayout(tusActividadesLayout);
        tusActividadesLayout.setHorizontalGroup(
            tusActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tusActividadesLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );
        tusActividadesLayout.setVerticalGroup(
            tusActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tusActividadesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(tusActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 730, -1));

        ejercicios.setBackground(new java.awt.Color(255, 255, 255));
        ejercicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("   Ejercicios regulares");

        javax.swing.GroupLayout ejerciciosLayout = new javax.swing.GroupLayout(ejercicios);
        ejercicios.setLayout(ejerciciosLayout);
        ejerciciosLayout.setHorizontalGroup(
            ejerciciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejerciciosLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 380, Short.MAX_VALUE))
        );
        ejerciciosLayout.setVerticalGroup(
            ejerciciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(ejercicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 730, 50));

        actividades.setBackground(new java.awt.Color(255, 255, 255));
        actividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("   Actividades");

        javax.swing.GroupLayout actividadesLayout = new javax.swing.GroupLayout(actividades);
        actividades.setLayout(actividadesLayout);
        actividadesLayout.setHorizontalGroup(
            actividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividadesLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        actividadesLayout.setVerticalGroup(
            actividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actividadesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(actividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 730, 50));

        pasos.setBackground(new java.awt.Color(255, 255, 255));
        pasos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("   Pasos");

        javax.swing.GroupLayout pasosLayout = new javax.swing.GroupLayout(pasos);
        pasos.setLayout(pasosLayout);
        pasosLayout.setHorizontalGroup(
            pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasosLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        pasosLayout.setVerticalGroup(
            pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasosLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(pasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 730, 50));

        resumen.setBackground(new java.awt.Color(255, 255, 255));
        resumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("   Resumen");

        javax.swing.GroupLayout resumenLayout = new javax.swing.GroupLayout(resumen);
        resumen.setLayout(resumenLayout);
        resumenLayout.setHorizontalGroup(
            resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumenLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        resumenLayout.setVerticalGroup(
            resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resumenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        registrarActividades.setBackground(new java.awt.Color(255, 255, 255));
        registrarActividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("                       Registrar actividades");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout registrarActividadesLayout = new javax.swing.GroupLayout(registrarActividades);
        registrarActividades.setLayout(registrarActividadesLayout);
        registrarActividadesLayout.setHorizontalGroup(
            registrarActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarActividadesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        registrarActividadesLayout.setVerticalGroup(
            registrarActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarActividadesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(registrarActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 330, 40));

        tusActividades1.setBackground(new java.awt.Color(133, 193, 233));
        tusActividades1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("   Tus metas");

        javax.swing.GroupLayout tusActividades1Layout = new javax.swing.GroupLayout(tusActividades1);
        tusActividades1.setLayout(tusActividades1Layout);
        tusActividades1Layout.setHorizontalGroup(
            tusActividades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tusActividades1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );
        tusActividades1Layout.setVerticalGroup(
            tusActividades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tusActividades1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(tusActividades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        pasos1.setBackground(new java.awt.Color(255, 255, 255));
        pasos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("   Metas cercanas");

        javax.swing.GroupLayout pasos1Layout = new javax.swing.GroupLayout(pasos1);
        pasos1.setLayout(pasos1Layout);
        pasos1Layout.setHorizontalGroup(
            pasos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasos1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        pasos1Layout.setVerticalGroup(
            pasos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasos1Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(pasos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 730, 50));

        actividades1.setBackground(new java.awt.Color(255, 255, 255));
        actividades1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("   Metas de comida");

        javax.swing.GroupLayout actividades1Layout = new javax.swing.GroupLayout(actividades1);
        actividades1.setLayout(actividades1Layout);
        actividades1Layout.setHorizontalGroup(
            actividades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividades1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        actividades1Layout.setVerticalGroup(
            actividades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actividades1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(actividades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 730, 50));

        ejercicios1.setBackground(new java.awt.Color(255, 255, 255));
        ejercicios1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("   Metas de actividades");

        javax.swing.GroupLayout ejercicios1Layout = new javax.swing.GroupLayout(ejercicios1);
        ejercicios1.setLayout(ejercicios1Layout);
        ejercicios1Layout.setHorizontalGroup(
            ejercicios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejercicios1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 380, Short.MAX_VALUE))
        );
        ejercicios1Layout.setVerticalGroup(
            ejercicios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(ejercicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 730, 50));

        resumen1.setBackground(new java.awt.Color(255, 255, 255));
        resumen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Coolvetica Compressed Hv", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("   Tus recompensas");

        javax.swing.GroupLayout resumen1Layout = new javax.swing.GroupLayout(resumen1);
        resumen1.setLayout(resumen1Layout);
        resumen1Layout.setHorizontalGroup(
            resumen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumen1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        resumen1Layout.setVerticalGroup(
            resumen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resumen1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(resumen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 860, 730, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opcion;
    private javax.swing.JPanel TComidas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel actividades;
    private javax.swing.JPanel actividades1;
    private javax.swing.JPanel almuerzo;
    private javax.swing.JPanel añadirAlimentos1;
    private javax.swing.JPanel cena;
    private javax.swing.JPanel desayuno;
    private javax.swing.JPanel ejercicios;
    private javax.swing.JPanel ejercicios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel pasos;
    private javax.swing.JPanel pasos1;
    private javax.swing.JPanel registrarActividades;
    private javax.swing.JPanel resumen;
    private javax.swing.JPanel resumen1;
    private javax.swing.JPanel tusActividades;
    private javax.swing.JPanel tusActividades1;
    // End of variables declaration//GEN-END:variables
}
